version: '2'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=anagram
      - MYSQL_DATABASE=anagram
      - MYSQL_USER=anagram
      - MYSQL_PASSWORD=anagram
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: web
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"